<?php
$langues = array(
	'langue' => 'Ελληνικά',
	'locale' => 'hellenic',
	'addVirtual' => 'Προσθήκη ενός VirtualHost',
	'backHome' => 'Επιστροφή στην Αρχική σελίδα',
	'VirtualSubMenuOn' => 'Το αντικείμενο <code>υπομενού VirtualHost</code> πρέπει να τεθεί σε (Ανοιχτό) στις <code>Ρυθμίσεις Wamp</code> Μενού Δεξιού Κλικ. Μετά επαναφορτώστε αυτή τη σελίδα',
	'UncommentInclude' => 'Αποσχολιάστε <small>(Σβήστε τη δίεση #)</small> τη γραμμή <code>#Include conf/extra/httpd-vhosts.conf</code><br>στο αρχείο %s',
	'FileNotExists' => 'Το αρχείο <code>%s</code> δεν υπάρχει',
	'txtTLDdev' => 'Το Όνομα Διακομιστή %s χρησιμοποιεί το TLD %s που μονοπωλείται από τους φυλλομετρητές ιστού. Χρησιμοποιήστε άλλο TLD (για παράδειγμα .test)',
	'FileNotWritable' => 'Το αρχείο <code>%s</code> δεν είναι εγγράψιμο',
	'DirNotExists' => 'Το <code>%s</code> δεν υπάρχει ή δεν είναι φάκελος',
	'NotwwwDir' => 'Ο φάκελος <code>%s</code> είναι δεσμευμένος για το «localhost». Χρησιμοποιήστε άλλο φάκελο.',
	'NotCleaned' => 'Το αρχείο <code>%s</code> δεν εκκαθαρίστηκε.<br>Εκεί παραμένουν παραδείγματα VirtualHost όπως: dummy-host.example.com',
	'NoVirtualHost' => 'Δεν έχει οριστεί VirtualHost στο <code>%s</code><br>Πρέπει να υπάρχει τουλάχιστον το VirtualHost για το localhost.',
	'NoFirst' => 'Το πρώτο VirtualHost πρέπει να είναι το <code>localhost</code> στο αρχείο <code>%s</code>',
	'ServerNameInvalid' => 'Το όνομα διακομιστή ServerName <code>%s</code> δεν είναι έγκυρο.',
	'LocalIpInvalid' => 'Η τοπική IP <code>%s</code> δεν είναι έγκυρη.',
	'VirtualHostName' => 'Το όνομα του <code>Virtual Host</code> Όχι διακριτικοί χαρακτήρες (ecen) - Όχι κενό - Όχι κάτω παύλα (_)',
	'VirtualHostFolder' => 'Πλήρης απόλυτη <code>διαδρομή</code> του <code>φακέλου</code> του VirtualHost <i>Παραδείγματα: C:/wamp/www/projet/ ή E:/www/site1/</i>',
	'VirtualHostIP' => '<code class="option">Αν</code> θέλετε να χρησιμοποιήσετε VirtualHost με IP: <code class="option">τοπική IP</code> 127.x.y.z ',
	'VirtualHostPhpFCGI' => '<code class="option">Αν</code> θέλετε να χρησιμοποιήσετε PHP σε κατάσταση FCGI, οι <code class="option">Αποδεκτές εκδόσεις</code> παρακάτω ',
	'VirtualHostPort' => '<code class="option">Αν</code> θέλετε να χρησιμοποιήσετε «θύρα Ακρόασης» (Listen port) διαφορετική από τις προεπιλεγμένες <code class="option">Αποδεκτές θύρες</code> παρακάτω ',
	'VirtualHostPortNone' => 'Αν θέλετε να χρησιμοποιήσετε «θύρα Ακρόασης» (Listen port) διαφορετική από την προεπιλεγμένη, πρέπει να προσθέσετε μια Θύρα Ακρόασης στον Apache με τα Εργαλεία Δεξιού κλικ',
	'VirtualAlreadyExist' => 'Το όνομα διακοιστή ServerName <code>%s</code> υπάρχει ήδη',
	'VirtualIpAlreadyUsed' => 'Η τοπική IP <code>%s</code> υπάρχει ήδη',
	'VirtualPortNotExist' => 'Η θύρα <code>%s</code> δεν είναι «Θύρα ακρόασης» του Apache',
	'VirtualPortExist' => 'Η θύρα <code>%s</code> είναι η προεπιλεγμένη «Θύρα ακρόασης» του Apache δεν πρέπει να αναφέρεται',
	'VirtualHostExists' => 'Το VirtualHost έχει ήδη οριστεί:',
	'Start' => 'Έναρξη δημιουργίας/αλλαγής του VirtualHost (Ίσως διαρκέσει λίγο...)',
	'StartAlias' => 'Έναρξη αλλαγής της Ετικέτας',
	'GreenErrors' => 'Τα σφάλματα σε πράσινο πλαίσιο μπορούν να διορθωθούν αυτόματα.',
	'Correct' => 'Έναρξη της αυτόματης διόρθωσης των σφαλμάτων εντός των πράσινων πλαισίων',
	'NoModify' => 'Αδύνατη η αλλαγή των αρχείων <code>httpd-vhosts.conf</code> ή <code>hosts</code>',
	'NoModifyAlias' => 'Η Ετικέτα δεν έχει αλλαχτεί',
	'VirtualCreated' => 'Τα αρχεία έχουν αλλάξει. Το Virtual host <code>%s</code> δημιουργήθηκε/άλλαξε',
	'ModifiedAlias' => 'Η Ετικέτα <code>%s</code> αλλάχτηκε',
	'CommandMessage' => 'Μηνύματα από τη γραμμή εντολών για ενημέρωση του DNS:',
	'However' => 'Μπορείτε να προσθέσετε/αλλάξετε ένα άλλο VirtualHost πατώντας το «Προσθήκη ενός VirtualHost».<br>Ωστόσο, για αυτά τα νέα VirtualHost που λαμβάνονται υπόψη από τον Apache, πρέπει να εκτελέσετε την επιλογή <br><code>Επανεκκίνηση DNS</code><br>από το μενού Εργαλείων Δεξιού Κλικ του εικονιδίου Wampmanager. <i>(Αυτό δυστυχώς δεν μπορεί να γίνει αυτόματα)</i>',
	'HoweverAlias' => 'Μπορείτε να αλλάξετε μια Ετικέτα, πατώντας το «Προσθήκη ενός VirtualHost».<br>Ωστόοσ, αυτές τις αλλαγμένες Ετικέτες για να ληφθούν υπόψη από τον Wampmanager (Apache), πρέπει να εκτελέσετε το <br><code>Επανεκκίνηση DNS</code><br>από τα Εργαλεία του μενού Δεξιού κλικ του εικονιδίου Wampmanager.</i>',
	'HoweverWamp' => 'Το δημιουργημένο/αλλαγμένο VirtualHost έχει ληφθεί υπόψη από τον Apache.<br>Μπορείτε να προσθέσετε/αλλάξετε ένα VirtualHost πατώντας το «Προσθήκη ενός VirtualHost».<br>Μπορείτε να ξεκινήσετε να εργάζεστε σε αυτό το νέο VirtualHost.<br>Αλλά για να ληφθούν υπόψη αυτά τα νέα VirtualHosts από τα μενού του Wampmanager, πρέπει να πατήσετε<br><code>Ανανέωση</code><br>από το μενού Δεξιού κλικ του εικονιδίου του Wampmanager.</i>',
	'suppForm' => 'Διαγραφή φόρμας VirtualHost',
	'suppVhost' => 'Διαγραφή VirtualHost',
	'modifyForm' => 'Φόρμα αλλαγής VirtualHost',
	'modifyVhost' => 'Αλλαγή VirtualHost',
	'modAliasForm' => 'Φόρμα Αλλαγής Ετικέτας',
	'modifyAlias' => 'Αλλαγή Ετικέτας',
	'Required' => 'Απαιτείται',
	'Optional' => 'Προαιρετικό',
	'phpNotExists' => 'Η έκδοση PHP δεν υπάρχει',
);

?>