<?php
// 3.2.5 - pievienota dokumentācija valodām, kurām tas nepieciešams
// angļu valodai ir identiska dokumentācijai

$langues = array(
	'langue' => 'latviešu valoda',
	'locale' => 'latviešu valoda',
	'titreHtml' => 'WAMPSERVER mājas lapa',
	'titreConf' => 'Servera konfigurācija',
	'versa' => 'Apache versija:',
	'doca2.2' => 'httpd.apache.org/docs/2.2/en/',
	'doca2.4' => 'httpd.apache.org/docs/2.4/en/',
	'versp' => 'PHP versija:',
	'server' => 'Servera programmatūra:',
	'documentation' => 'dokumentācija',
	'documentation-of' => 'dokumentācija',
	'docp' => 'www.php.net/manual/en/',
	'versm' => 'MySQL versija:',
	'docm' => 'dev.mysql.com/doc/index.html',
	'versmaria' => 'MariaDB versija: ',
	'docmaria' => 'mariadb.com/kb/en/mariadb/documentation',
	'phpExt' => 'Ielādēti paplašinājumi: ',
	'titrePage' => 'Rīki',
	'txtProjet' => 'Projekti',
	'txtNoProjet' => 'Vēl nav projektu.<br /> Lai izveidotu jaunu, vienkārši izveidojiet direktoriju mapē \'www\'.',
	'txtProjects' => 'Tās ir jūsu mapes %s<br />Lai tās izmantotu kā http saites, tās jādeklarē kā VirtualHost',
	'txtAlias' => 'Aizstājvārdi',
	'txtNoAlias' => 'Vēl nav aizstājvārda.<br /> Lai izveidotu jaunu, izmantojiet izvēlni WAMPSERVER. ',
	'txtVhost' => 'VirtualHost',
	'txtServerName' => 'Servera nosaukumam %s ir sintakses kļūda failā %s',
	'txtDocRoot' => 'Servera nosaukums %s izmanto DocumentRoot %s rezervēts localhost',
	'txtTLDdev' => 'Servera nosaukums %s izmanto TLD %s ko monopolizē tīmekļa pārlūkprogrammas. Izmantojiet citu TLD (piemēram, .test)',
	'txtServerNameIp' => 'IP %s servera nosaukumam %s failā nav derīgs %s',
	'txtVhostNotClean' => ' %s fails nav iztīrīts. Ir palikuši VirtualHost piemēri, piemēram: dummy-host.example.com',
	'txtNoVhost' => 'Vēl nav VirtualHost. Pievienojiet vienu katram faila projektam: wamp/bin apache/apache%s/conf/extra/httpd-vhosts.conf',
	'txtNoIncVhost' => 'Atceliet komentāru vai pievienojiet <i>Include conf/extra/httpd-vhosts.conf</i>failā wamp/bin/apache/apache%s/conf/httpd.conf',
	'txtNoVhostFile' => 'Fails: %s nepastāv',
	'txtNoPath' => 'Ceļš %s priekš %s neeksistē (File %s )',
	'txtNotWritable' => 'Fails: %s nav rakstāms',
	'txtNbNotEqual' => 'Skaits %s nesakrīt ar skaitu %s failā %s',
	'txtAddVhost' => 'Pievienot virtuālo resursdatoru',
	'txtPortNumber' => 'Porta numurs %s nav pareiza vērtība vai tas nav tāds pats kā failā %s',
	'txtCorrected' => 'Dažas VirtualHosts kļūdas var labot.',
	'forum' => 'Wampserver forums',
	'forumLink' => 'http://forum.wampserver.com/list.php?2',
	'portUsed' => 'Apache definētais ports: ',
	'mysqlportUsed' => 'MySQL definētais ports:',
	'mariaportUsed' => 'MariaDB definētais ports: ',
	'defaultDBMS' => 'noklusējuma DBMS',
	'HelpMySQLMariaDB' => 'Kā lietot MySQL vai MariaDB?<br>Kas ir noklusējuma DBMS?<br>Kā nomainīt noklusējuma DBMS?<br>Dodieties uz saistīto palīdzību: Ar peles labo pogu noklikšķiniet uz ikonas Wampmanager -> Palīdzība -> MariaDB - MySQL',
	'nolocalhost' => 'Tā ir slikta ideja projektu palaišanas url pievienot localhost. Vislabāk ir definēt VirtualHost<br />wamp/bin/apache/apache%s/conf/extra/httpd-vhosts.conf<br />failā, nevis localhost pievienot URL.',
	);
?>