<?php
// 3.1.4 - txtTLDdev
//

$langues = array(
	'langue' => 'Español',
	'locale' => 'español',
	'titreHtml' => 'Página de inicio de WAMPSERVER',
	'titreConf' => 'Configuración del servidor',
	'versa' => 'Versión de Apache:',
	'doca2.2' => 'httpd.apache.org/docs/2.2/es/',
	'doca2.4' => 'httpd.apache.org/docs/2.4/es/',
	'versp' => 'Versión de PHP:',
	'server' => 'Software del servidor:',
	'documentation' => 'Documentación',
	'docp' => 'www.php.net/manual/es/',
	'versm' => 'Versión de MySQL:',
	'docm' => 'dev.mysql.com/doc/index.html',
	'versmaria' => 'Versión de MariaDB: ',
	'docmaria' => 'mariadb.com/kb/en/mariadb/documentation',
	'phpExt' => 'Extensiones cargadas: ',
	'titrePage' => 'Herramientas',
	'txtProjet' => 'Tus proyectos',
	'txtNoProjet' => 'Aún no hay proyectos.<br/>Para crear uno nuevo, solo crea un directorio en \www\.',
	'txtAlias' => 'Tus alias',
	'txtNoAlias' => 'Aún no hay alias. <br /> Para crear uno nuevo, use el menú de WAMPSERVER.',
	'txtVhost' => 'Tu VirtualHost',
	'txtServerName' => 'El ServerName %s tiene un error de sintaxis en el archivo %s',
	'txtDocRoot' => 'El ServerName %s usa DocumentRoot %s reservado para localhost',
	'txtTLDdev' => 'ServerName %s usa TLD %s, que está monopolizado por los navegadores web. Utilice otro TLD (.test por ejemplo)',
	'txtServerNameIp' => 'IP %s del Servername %s no es válida en el archivo %s',
	'txtVhostNotClean' => 'El archivo %s no se ha limpiado. Quedan ejemplos de VirtualHost como: dummy-host.example.com',
	'txtNoVhost' => 'No hay VirtualHost todavía. Agregue uno para cada proyecto en el archivo wamp/bin/apache/apache%s/conf/extra/httpd-vhosts.conf',
	'txtNoIncVhost' => 'Descomentar o añadir <i>Include conf/extra/httpd-vhosts.conf</i> en el archivo wamp/bin/apache/apache%s/conf/httpd.conf',
	'txtNoVhostFile' => 'El archivo: %s no existe',
	'txtNoPath' => 'La ruta %s para %s no existe (archivo %s)',
	'txtNotWritable' => 'El archivo: %s es de solo lectura',
	'txtNbNotEqual' => 'El número de %s no coincide con el número de %s en el archivo %s',
	'txtAddVhost' => 'Añadir un host virtual',
	'txtPortNumber' => 'El número de puerto para %s no tiene el valor correcto o no es el mismo en el archivo %s',
	'txtCorrected' => 'Algunos errores de VirtualHosts pueden ser corregidos.',
	'forum' => 'Foro de Wampserver',
	'forumLink' => 'http://forum.wampserver.com/list.php?2',
	'portUsed' => 'Puerto definido para Apache: ',
	'mysqlportUsed' => 'Puerto definido para MySQL: ',
	'mariaportUsed' => 'Puerto definido para MariaDB: ',
	'nolocalhost' => 'Es una mala idea añadir localhost en la url de lanzamiento de proyectos. Es mejor definir VirtualHost en el archivo<br/>wamp/bin/apache/apache%s/conf/extra/httpd-vhosts.conf<br/> y no añadir localhost en la url.',
	);
?>