<?php
// 3.2.5 - documentation-of added for languages requiring it
// for English is identical to documentation

$langues = array(
	'langue' => 'Български',
	'locale' => 'България',
	'titreHtml' => 'Начална страница на WAMPSERVER',
	'titreConf' => 'Конфигурация на сървъра',
	'versa' => 'Версия на Apache:',
	'doca2.2' => 'httpd.apache.org/docs/2.2/en/',
	'doca2.4' => 'httpd.apache.org/docs/2.4/en/',
	'versp' => 'Версия на PHP:',
	'server' => 'Софтуер на сървъра:',
	'documentation' => 'Документация',
	'documentation-of' => 'Документация на',
	'docp' => 'www.php.net/manual/en/',
	'versm' => 'Версия на MySQL:',
	'docm' => 'dev.mysql.com/doc/index.html',
	'versmaria' => 'Версия на MariaDB: ',
	'docmaria' => 'mariadb.com/kb/en/mariadb/documentation',
	'phpExt' => 'Заредени разширения: ',
	'titrePage' => 'Инструменти',
	'txtProjet' => 'Проекти',
	'txtNoProjet' => 'Все още нямаш никакви проекти.<br />За да създадеш нов проект, просто му създай папка в www.',
	'txtProjects' => 'Това са твоите папки в %s.<br />За да ги използваш като връзки, трябва да ги декларираш като виртуални хостове.',
	'txtAlias' => 'Псевдоними',
	'txtNoAlias' => 'Все още нямаш псевдоними.<br />За да създадеш нов, използвай менюто на WAMPSERVER.',
	'txtVhost' => 'Виртуални хостове',
	'txtServerName' => 'Има синтактична грешка в името на сървъра %s във файла %s.',
	'txtDocRoot' => 'Името на сървъра %s използва основна директория за документи %s, която е запазена за localhost.',
	'txtTLDdev' => 'Името на сървъра %s използва TLD %s, който е монополизиран от браузърите. Използвай друг TLD (например .test).',
	'txtServerNameIp' => 'IP адресът %s за сървър %s е невалиден във файла %s.',
	'txtVhostNotClean' => 'Файлът %s не е изчистен. В него са останали виртуални хостове от рода на: dummy-host.example.com.',
	'txtNoVhost' => 'Все още нямаш виртуални хостове. Създай виртуален хост за всеки от проектите в следния файл: wamp/bin/apache/apache%s/conf/extra/httpd-vhosts.conf',
	'txtNoIncVhost' => 'Разкоментирай или добави <i>Include conf/extra/httpd-vhosts.conf</i> във файла wamp/bin/apache/apache%s/conf/httpd.conf',
	'txtNoVhostFile' => 'Файлът %s не съществува.',
	'txtNoPath' => 'Пътят %s за %s не съществува (файл%s).',
	'txtNotWritable' => 'Във файла %s не може да се пише.',
	'txtNbNotEqual' => 'Броят %s не отговаря на броя %s във файла %s.',
	'txtAddVhost' => 'Нов виртуален хост',
	'txtPortNumber' => 'Номерът на порта за %s е неправилен или е различен от този във файла %s.',
	'txtCorrected' => 'Някои грешки при виртуалните хостове могат да бъдат поправени.',
	'forum' => 'Форум на WampServer',
	'forumLink' => 'http://forum.wampserver.com/list.php?2',
	'portUsed' => 'Определен за Apache порт: ',
	'mysqlportUsed' => 'Определен за MySQL порт: ',
	'mariaportUsed' => 'Определен за MariaDB порт: ',
	'defaultDBMS' => 'Стандартна СУБД:',
	'HelpMySQLMariaDB' => 'Как се използва MySQL и/или MariaDB?<br>Какво означава стандартна СУБД?<br>Как да променя стандартната СУБД?<br>Отиди на съответната помощ: Кликни с десен бутон върху иконата на WampManager > Помощ > MariaDB - MySQL.',
	'nolocalhost' => 'Не е добра идея да добавяш localhost към адреса на проектите. Най-добре е да дефинираш виртуални хостове във файла<br />wamp/bin/apache/apache%s/conf/extra/httpd-vhosts.conf<br />и да не добавяш localhost към адреса.',
	);
?>